

# 서버 포트 설정
server:
  port: 8082


# database 연동 설정
spring:
  # MyBatis 설정
  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/BoardMapper.xml
    type-aliases-package: com.codingrecipe.board.entity


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none



